Repository FAP-Cloud-Service/FAP-Backend, pull requests merged in 2021-05, with the labels that each got.

#51 Check for HTTP 204 instead of HTTP 200
  FriendsAndPlaces/Helpers/Database/DatabaseManager.cs
Labels: bug

#52 Release
  FriendsAndPlaces/Helpers/Database/DatabaseManager.cs
Labels: bug

#54 Only save hashed passwords in database
  FriendsAndPlaces/Functions/LoginFunction.cs
  FriendsAndPlaces/Helpers/Database/DatabaseManager.cs
  FriendsAndPlaces/Helpers/Hashing/HashManager.cs
  FriendsAndPlaces/Helpers/Hashing/IHashManager.cs
  FriendsAndPlaces/Startup.cs
Labels: PRIORITY, bug, security

#55 Release Hashing
  FriendsAndPlaces/Functions/LoginFunction.cs
  FriendsAndPlaces/Helpers/Database/DatabaseManager.cs
  FriendsAndPlaces/Helpers/Hashing/HashManager.cs
  FriendsAndPlaces/Helpers/Hashing/IHashManager.cs
  FriendsAndPlaces/Startup.cs
Labels: Release
